# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 07:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.TextField(verbose_name='Название группы вопросов')),
            ],
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField(verbose_name='Номер вопрос')),
                ('question_name', models.TextField(verbose_name='Вопрос')),
                ('question_answer', models.TextField(blank=True, null=True, verbose_name='Ответ на вопрос')),
                ('question_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='answers.group')),
            ],
        ),
    ]
